// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vaultfs/v1/admin.proto

package vaultfsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeState is the liveness of a chunk server as seen by the master.
type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED NodeState = 0
	NodeState_NODE_STATE_ALIVE       NodeState = 1
	NodeState_NODE_STATE_DEAD        NodeState = 2
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_ALIVE",
		2: "NODE_STATE_DEAD",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED": 0,
		"NODE_STATE_ALIVE":       1,
		"NODE_STATE_DEAD":        2,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_vaultfs_v1_admin_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_vaultfs_v1_admin_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{0}
}

type NodeStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Node              *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	State             NodeState              `protobuf:"varint,2,opt,name=state,proto3,enum=vaultfs.v1.NodeState" json:"state,omitempty"`
	ChunkCount        int64                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,4,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStatus) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeStatus) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeStatus) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *NodeStatus) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	FileCount     int64                  `protobuf:"varint,3,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	ChunkCount    int64                  `protobuf:"varint,4,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Nodes         []*NodeStatus          `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterStatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterStatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ClusterStatusResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *ClusterStatusResponse) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *ClusterStatusResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type TriggerGcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerGcRequest) Reset() {
	*x = TriggerGcRequest{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerGcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerGcRequest) ProtoMessage() {}

func (x *TriggerGcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerGcRequest.ProtoReflect.Descriptor instead.
func (*TriggerGcRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{3}
}

type TriggerGcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerGcResponse) Reset() {
	*x = TriggerGcResponse{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerGcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerGcResponse) ProtoMessage() {}

func (x *TriggerGcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerGcResponse.ProtoReflect.Descriptor instead.
func (*TriggerGcResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerGcResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeStatus          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_vaultfs_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_vaultfs_v1_admin_proto protoreflect.FileDescriptor

const file_vaultfs_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x16vaultfs/v1/admin.proto\x12\n" +
	"vaultfs.v1\x1a\x16vaultfs/v1/types.proto\"\xb4\x01\n" +
	"\n" +
	"NodeStatus\x12(\n" +
	"\x04node\x18\x01 \x01(\v2\x14.vaultfs.v1.NodeInfoR\x04node\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.vaultfs.v1.NodeStateR\x05state\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x03R\n" +
	"chunkCount\x12.\n" +
	"\x13last_heartbeat_unix\x18\x04 \x01(\x03R\x11lastHeartbeatUnix\"\x16\n" +
	"\x14ClusterStatusRequest\"\xb6\x01\n" +
	"\x15ClusterStatusResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1d\n" +
	"\n" +
	"file_count\x18\x03 \x01(\x03R\tfileCount\x12\x1f\n" +
	"\vchunk_count\x18\x04 \x01(\x03R\n" +
	"chunkCount\x12,\n" +
	"\x05nodes\x18\x05 \x03(\v2\x16.vaultfs.v1.NodeStatusR\x05nodes\"\x12\n" +
	"\x10TriggerGcRequest\"-\n" +
	"\x11TriggerGcResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\"\x12\n" +
	"\x10ListNodesRequest\"A\n" +
	"\x11ListNodesResponse\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.vaultfs.v1.NodeStatusR\x05nodes*R\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x01\x12\x13\n" +
	"\x0fNODE_STATE_DEAD\x10\x022\xf8\x01\n" +
	"\fAdminService\x12T\n" +
	"\rClusterStatus\x12 .vaultfs.v1.ClusterStatusRequest\x1a!.vaultfs.v1.ClusterStatusResponse\x12H\n" +
	"\tTriggerGc\x12\x1c.vaultfs.v1.TriggerGcRequest\x1a\x1d.vaultfs.v1.TriggerGcResponse\x12H\n" +
	"\tListNodes\x12\x1c.vaultfs.v1.ListNodesRequest\x1a\x1d.vaultfs.v1.ListNodesResponseB\xa0\x01\n" +
	"\x0ecom.vaultfs.v1B\n" +
	"AdminProtoP\x01Z9github.com/sumanthd032/vaultfs/proto/vaultfs/v1;vaultfsv1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vaultfs.V1\xca\x02\n" +
	"Vaultfs\\V1\xe2\x02\x16Vaultfs\\V1\\GPBMetadata\xea\x02\vVaultfs::V1b\x06proto3"

var (
	file_vaultfs_v1_admin_proto_rawDescOnce sync.Once
	file_vaultfs_v1_admin_proto_rawDescData []byte
)

func file_vaultfs_v1_admin_proto_rawDescGZIP() []byte {
	file_vaultfs_v1_admin_proto_rawDescOnce.Do(func() {
		file_vaultfs_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultfs_v1_admin_proto_rawDesc), len(file_vaultfs_v1_admin_proto_rawDesc)))
	})
	return file_vaultfs_v1_admin_proto_rawDescData
}

var file_vaultfs_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vaultfs_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vaultfs_v1_admin_proto_goTypes = []any{
	(NodeState)(0),                // 0: vaultfs.v1.NodeState
	(*NodeStatus)(nil),            // 1: vaultfs.v1.NodeStatus
	(*ClusterStatusRequest)(nil),  // 2: vaultfs.v1.ClusterStatusRequest
	(*ClusterStatusResponse)(nil), // 3: vaultfs.v1.ClusterStatusResponse
	(*TriggerGcRequest)(nil),      // 4: vaultfs.v1.TriggerGcRequest
	(*TriggerGcResponse)(nil),     // 5: vaultfs.v1.TriggerGcResponse
	(*ListNodesRequest)(nil),      // 6: vaultfs.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 7: vaultfs.v1.ListNodesResponse
	(*NodeInfo)(nil),              // 8: vaultfs.v1.NodeInfo
}
var file_vaultfs_v1_admin_proto_depIdxs = []int32{
	8, // 0: vaultfs.v1.NodeStatus.node:type_name -> vaultfs.v1.NodeInfo
	0, // 1: vaultfs.v1.NodeStatus.state:type_name -> vaultfs.v1.NodeState
	1, // 2: vaultfs.v1.ClusterStatusResponse.nodes:type_name -> vaultfs.v1.NodeStatus
	1, // 3: vaultfs.v1.ListNodesResponse.nodes:type_name -> vaultfs.v1.NodeStatus
	2, // 4: vaultfs.v1.AdminService.ClusterStatus:input_type -> vaultfs.v1.ClusterStatusRequest
	4, // 5: vaultfs.v1.AdminService.TriggerGc:input_type -> vaultfs.v1.TriggerGcRequest
	6, // 6: vaultfs.v1.AdminService.ListNodes:input_type -> vaultfs.v1.ListNodesRequest
	3, // 7: vaultfs.v1.AdminService.ClusterStatus:output_type -> vaultfs.v1.ClusterStatusResponse
	5, // 8: vaultfs.v1.AdminService.TriggerGc:output_type -> vaultfs.v1.TriggerGcResponse
	7, // 9: vaultfs.v1.AdminService.ListNodes:output_type -> vaultfs.v1.ListNodesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vaultfs_v1_admin_proto_init() }
func file_vaultfs_v1_admin_proto_init() {
	if File_vaultfs_v1_admin_proto != nil {
		return
	}
	file_vaultfs_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultfs_v1_admin_proto_rawDesc), len(file_vaultfs_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaultfs_v1_admin_proto_goTypes,
		DependencyIndexes: file_vaultfs_v1_admin_proto_depIdxs,
		EnumInfos:         file_vaultfs_v1_admin_proto_enumTypes,
		MessageInfos:      file_vaultfs_v1_admin_proto_msgTypes,
	}.Build()
	File_vaultfs_v1_admin_proto = out.File
	file_vaultfs_v1_admin_proto_goTypes = nil
	file_vaultfs_v1_admin_proto_depIdxs = nil
}
