// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vaultfs/v1/chunk.proto

package vaultfsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteChunkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChunkId string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data    []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// downstream lists the remaining chunk servers in the replication chain. The
	// receiver stores the chunk, then forwards it to downstream[0] with the rest
	// as that node's chain.
	Downstream    []string `protobuf:"bytes,3,rep,name=downstream,proto3" json:"downstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *WriteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *WriteChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteChunkRequest) GetDownstream() []string {
	if x != nil {
		return x.Downstream
	}
	return nil
}

type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *WriteChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *ReadChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{5}
}

type ReplicateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkRequest) Reset() {
	*x = ReplicateChunkRequest{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkRequest) ProtoMessage() {}

func (x *ReplicateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkRequest.ProtoReflect.Descriptor instead.
func (*ReplicateChunkRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicateChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicateChunkRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

type ReplicateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkResponse) Reset() {
	*x = ReplicateChunkResponse{}
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkResponse) ProtoMessage() {}

func (x *ReplicateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkResponse.ProtoReflect.Descriptor instead.
func (*ReplicateChunkResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

var File_vaultfs_v1_chunk_proto protoreflect.FileDescriptor

const file_vaultfs_v1_chunk_proto_rawDesc = "" +
	"\n" +
	"\x16vaultfs/v1/chunk.proto\x12\n" +
	"vaultfs.v1\"b\n" +
	"\x11WriteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"downstream\x18\x03 \x03(\tR\n" +
	"downstream\"/\n" +
	"\x12WriteChunkResponse\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"-\n" +
	"\x10ReadChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"'\n" +
	"\x11ReadChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x15\n" +
	"\x13DeleteChunkResponse\"Y\n" +
	"\x15ReplicateChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"3\n" +
	"\x16ReplicateChunkResponse\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId2\xce\x02\n" +
	"\fChunkService\x12K\n" +
	"\n" +
	"WriteChunk\x12\x1d.vaultfs.v1.WriteChunkRequest\x1a\x1e.vaultfs.v1.WriteChunkResponse\x12H\n" +
	"\tReadChunk\x12\x1c.vaultfs.v1.ReadChunkRequest\x1a\x1d.vaultfs.v1.ReadChunkResponse\x12N\n" +
	"\vDeleteChunk\x12\x1e.vaultfs.v1.DeleteChunkRequest\x1a\x1f.vaultfs.v1.DeleteChunkResponse\x12W\n" +
	"\x0eReplicateChunk\x12!.vaultfs.v1.ReplicateChunkRequest\x1a\".vaultfs.v1.ReplicateChunkResponseB\xa0\x01\n" +
	"\x0ecom.vaultfs.v1B\n" +
	"ChunkProtoP\x01Z9github.com/sumanthd032/vaultfs/proto/vaultfs/v1;vaultfsv1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vaultfs.V1\xca\x02\n" +
	"Vaultfs\\V1\xe2\x02\x16Vaultfs\\V1\\GPBMetadata\xea\x02\vVaultfs::V1b\x06proto3"

var (
	file_vaultfs_v1_chunk_proto_rawDescOnce sync.Once
	file_vaultfs_v1_chunk_proto_rawDescData []byte
)

func file_vaultfs_v1_chunk_proto_rawDescGZIP() []byte {
	file_vaultfs_v1_chunk_proto_rawDescOnce.Do(func() {
		file_vaultfs_v1_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultfs_v1_chunk_proto_rawDesc), len(file_vaultfs_v1_chunk_proto_rawDesc)))
	})
	return file_vaultfs_v1_chunk_proto_rawDescData
}

var file_vaultfs_v1_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vaultfs_v1_chunk_proto_goTypes = []any{
	(*WriteChunkRequest)(nil),      // 0: vaultfs.v1.WriteChunkRequest
	(*WriteChunkResponse)(nil),     // 1: vaultfs.v1.WriteChunkResponse
	(*ReadChunkRequest)(nil),       // 2: vaultfs.v1.ReadChunkRequest
	(*ReadChunkResponse)(nil),      // 3: vaultfs.v1.ReadChunkResponse
	(*DeleteChunkRequest)(nil),     // 4: vaultfs.v1.DeleteChunkRequest
	(*DeleteChunkResponse)(nil),    // 5: vaultfs.v1.DeleteChunkResponse
	(*ReplicateChunkRequest)(nil),  // 6: vaultfs.v1.ReplicateChunkRequest
	(*ReplicateChunkResponse)(nil), // 7: vaultfs.v1.ReplicateChunkResponse
}
var file_vaultfs_v1_chunk_proto_depIdxs = []int32{
	0, // 0: vaultfs.v1.ChunkService.WriteChunk:input_type -> vaultfs.v1.WriteChunkRequest
	2, // 1: vaultfs.v1.ChunkService.ReadChunk:input_type -> vaultfs.v1.ReadChunkRequest
	4, // 2: vaultfs.v1.ChunkService.DeleteChunk:input_type -> vaultfs.v1.DeleteChunkRequest
	6, // 3: vaultfs.v1.ChunkService.ReplicateChunk:input_type -> vaultfs.v1.ReplicateChunkRequest
	1, // 4: vaultfs.v1.ChunkService.WriteChunk:output_type -> vaultfs.v1.WriteChunkResponse
	3, // 5: vaultfs.v1.ChunkService.ReadChunk:output_type -> vaultfs.v1.ReadChunkResponse
	5, // 6: vaultfs.v1.ChunkService.DeleteChunk:output_type -> vaultfs.v1.DeleteChunkResponse
	7, // 7: vaultfs.v1.ChunkService.ReplicateChunk:output_type -> vaultfs.v1.ReplicateChunkResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vaultfs_v1_chunk_proto_init() }
func file_vaultfs_v1_chunk_proto_init() {
	if File_vaultfs_v1_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultfs_v1_chunk_proto_rawDesc), len(file_vaultfs_v1_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaultfs_v1_chunk_proto_goTypes,
		DependencyIndexes: file_vaultfs_v1_chunk_proto_depIdxs,
		MessageInfos:      file_vaultfs_v1_chunk_proto_msgTypes,
	}.Build()
	File_vaultfs_v1_chunk_proto = out.File
	file_vaultfs_v1_chunk_proto_goTypes = nil
	file_vaultfs_v1_chunk_proto_depIdxs = nil
}
