// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vaultfs/v1/master.proto

package vaultfsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{3}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{4}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{5}
}

func (x *StatResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type OpenForReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenForReadRequest) Reset() {
	*x = OpenForReadRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenForReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenForReadRequest) ProtoMessage() {}

func (x *OpenForReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenForReadRequest.ProtoReflect.Descriptor instead.
func (*OpenForReadRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{8}
}

func (x *OpenForReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenForReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	File  *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// locations gives the replica sites for each chunk in file.chunk_ids order.
	Locations     []*ChunkLocation `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenForReadResponse) Reset() {
	*x = OpenForReadResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenForReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenForReadResponse) ProtoMessage() {}

func (x *OpenForReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenForReadResponse.ProtoReflect.Descriptor instead.
func (*OpenForReadResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{9}
}

func (x *OpenForReadResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *OpenForReadResponse) GetLocations() []*ChunkLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type OpenForWriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// chunk_ids are the content addresses of the chunks the client intends to
	// write, in order. The master uses them to plan replica placement.
	ChunkIds      []string `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenForWriteRequest) Reset() {
	*x = OpenForWriteRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenForWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenForWriteRequest) ProtoMessage() {}

func (x *OpenForWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenForWriteRequest.ProtoReflect.Descriptor instead.
func (*OpenForWriteRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{10}
}

func (x *OpenForWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenForWriteRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type OpenForWriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// placements gives the target chunk servers for each requested chunk.
	Placements    []*ChunkLocation `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenForWriteResponse) Reset() {
	*x = OpenForWriteResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenForWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenForWriteResponse) ProtoMessage() {}

func (x *OpenForWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenForWriteResponse.ProtoReflect.Descriptor instead.
func (*OpenForWriteResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{11}
}

func (x *OpenForWriteResponse) GetPlacements() []*ChunkLocation {
	if x != nil {
		return x.Placements
	}
	return nil
}

type FinalizeWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeWriteRequest) Reset() {
	*x = FinalizeWriteRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWriteRequest) ProtoMessage() {}

func (x *FinalizeWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWriteRequest.ProtoReflect.Descriptor instead.
func (*FinalizeWriteRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizeWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FinalizeWriteRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *FinalizeWriteRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FinalizeWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeWriteResponse) Reset() {
	*x = FinalizeWriteResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWriteResponse) ProtoMessage() {}

func (x *FinalizeWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWriteResponse.ProtoReflect.Descriptor instead.
func (*FinalizeWriteResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{13}
}

func (x *FinalizeWriteResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type GetLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseRequest) Reset() {
	*x = GetLeaseRequest{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseRequest) ProtoMessage() {}

func (x *GetLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetLeaseRequest) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{14}
}

func (x *GetLeaseRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetLeaseRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

type GetLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseResponse) Reset() {
	*x = GetLeaseResponse{}
	mi := &file_vaultfs_v1_master_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseResponse) ProtoMessage() {}

func (x *GetLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_master_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseResponse.ProtoReflect.Descriptor instead.
func (*GetLeaseResponse) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_master_proto_rawDescGZIP(), []int{15}
}

func (x *GetLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

var File_vaultfs_v1_master_proto protoreflect.FileDescriptor

const file_vaultfs_v1_master_proto_rawDesc = "" +
	"\n" +
	"\x17vaultfs/v1/master.proto\x12\n" +
	"vaultfs.v1\x1a\x16vaultfs/v1/types.proto\"'\n" +
	"\x11CreateFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\x12CreateFileResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.vaultfs.v1.FileInfoR\x04file\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x14\n" +
	"\x12DeleteFileResponse\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"8\n" +
	"\fStatResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.vaultfs.v1.FileInfoR\x04file\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\x0fListDirResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.vaultfs.v1.FileInfoR\aentries\"(\n" +
	"\x12OpenForReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"x\n" +
	"\x13OpenForReadResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.vaultfs.v1.FileInfoR\x04file\x127\n" +
	"\tlocations\x18\x02 \x03(\v2\x19.vaultfs.v1.ChunkLocationR\tlocations\"F\n" +
	"\x13OpenForWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\"Q\n" +
	"\x14OpenForWriteResponse\x129\n" +
	"\n" +
	"placements\x18\x01 \x03(\v2\x19.vaultfs.v1.ChunkLocationR\n" +
	"placements\"[\n" +
	"\x14FinalizeWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"A\n" +
	"\x15FinalizeWriteResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.vaultfs.v1.FileInfoR\x04file\"D\n" +
	"\x0fGetLeaseRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\";\n" +
	"\x10GetLeaseResponse\x12'\n" +
	"\x05lease\x18\x01 \x01(\v2\x11.vaultfs.v1.LeaseR\x05lease2\xe8\x04\n" +
	"\rMasterService\x12K\n" +
	"\n" +
	"CreateFile\x12\x1d.vaultfs.v1.CreateFileRequest\x1a\x1e.vaultfs.v1.CreateFileResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.vaultfs.v1.DeleteFileRequest\x1a\x1e.vaultfs.v1.DeleteFileResponse\x129\n" +
	"\x04Stat\x12\x17.vaultfs.v1.StatRequest\x1a\x18.vaultfs.v1.StatResponse\x12B\n" +
	"\aListDir\x12\x1a.vaultfs.v1.ListDirRequest\x1a\x1b.vaultfs.v1.ListDirResponse\x12N\n" +
	"\vOpenForRead\x12\x1e.vaultfs.v1.OpenForReadRequest\x1a\x1f.vaultfs.v1.OpenForReadResponse\x12Q\n" +
	"\fOpenForWrite\x12\x1f.vaultfs.v1.OpenForWriteRequest\x1a .vaultfs.v1.OpenForWriteResponse\x12T\n" +
	"\rFinalizeWrite\x12 .vaultfs.v1.FinalizeWriteRequest\x1a!.vaultfs.v1.FinalizeWriteResponse\x12E\n" +
	"\bGetLease\x12\x1b.vaultfs.v1.GetLeaseRequest\x1a\x1c.vaultfs.v1.GetLeaseResponseB\xa1\x01\n" +
	"\x0ecom.vaultfs.v1B\vMasterProtoP\x01Z9github.com/sumanthd032/vaultfs/proto/vaultfs/v1;vaultfsv1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vaultfs.V1\xca\x02\n" +
	"Vaultfs\\V1\xe2\x02\x16Vaultfs\\V1\\GPBMetadata\xea\x02\vVaultfs::V1b\x06proto3"

var (
	file_vaultfs_v1_master_proto_rawDescOnce sync.Once
	file_vaultfs_v1_master_proto_rawDescData []byte
)

func file_vaultfs_v1_master_proto_rawDescGZIP() []byte {
	file_vaultfs_v1_master_proto_rawDescOnce.Do(func() {
		file_vaultfs_v1_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultfs_v1_master_proto_rawDesc), len(file_vaultfs_v1_master_proto_rawDesc)))
	})
	return file_vaultfs_v1_master_proto_rawDescData
}

var file_vaultfs_v1_master_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_vaultfs_v1_master_proto_goTypes = []any{
	(*CreateFileRequest)(nil),     // 0: vaultfs.v1.CreateFileRequest
	(*CreateFileResponse)(nil),    // 1: vaultfs.v1.CreateFileResponse
	(*DeleteFileRequest)(nil),     // 2: vaultfs.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),    // 3: vaultfs.v1.DeleteFileResponse
	(*StatRequest)(nil),           // 4: vaultfs.v1.StatRequest
	(*StatResponse)(nil),          // 5: vaultfs.v1.StatResponse
	(*ListDirRequest)(nil),        // 6: vaultfs.v1.ListDirRequest
	(*ListDirResponse)(nil),       // 7: vaultfs.v1.ListDirResponse
	(*OpenForReadRequest)(nil),    // 8: vaultfs.v1.OpenForReadRequest
	(*OpenForReadResponse)(nil),   // 9: vaultfs.v1.OpenForReadResponse
	(*OpenForWriteRequest)(nil),   // 10: vaultfs.v1.OpenForWriteRequest
	(*OpenForWriteResponse)(nil),  // 11: vaultfs.v1.OpenForWriteResponse
	(*FinalizeWriteRequest)(nil),  // 12: vaultfs.v1.FinalizeWriteRequest
	(*FinalizeWriteResponse)(nil), // 13: vaultfs.v1.FinalizeWriteResponse
	(*GetLeaseRequest)(nil),       // 14: vaultfs.v1.GetLeaseRequest
	(*GetLeaseResponse)(nil),      // 15: vaultfs.v1.GetLeaseResponse
	(*FileInfo)(nil),              // 16: vaultfs.v1.FileInfo
	(*ChunkLocation)(nil),         // 17: vaultfs.v1.ChunkLocation
	(*Lease)(nil),                 // 18: vaultfs.v1.Lease
}
var file_vaultfs_v1_master_proto_depIdxs = []int32{
	16, // 0: vaultfs.v1.CreateFileResponse.file:type_name -> vaultfs.v1.FileInfo
	16, // 1: vaultfs.v1.StatResponse.file:type_name -> vaultfs.v1.FileInfo
	16, // 2: vaultfs.v1.ListDirResponse.entries:type_name -> vaultfs.v1.FileInfo
	16, // 3: vaultfs.v1.OpenForReadResponse.file:type_name -> vaultfs.v1.FileInfo
	17, // 4: vaultfs.v1.OpenForReadResponse.locations:type_name -> vaultfs.v1.ChunkLocation
	17, // 5: vaultfs.v1.OpenForWriteResponse.placements:type_name -> vaultfs.v1.ChunkLocation
	16, // 6: vaultfs.v1.FinalizeWriteResponse.file:type_name -> vaultfs.v1.FileInfo
	18, // 7: vaultfs.v1.GetLeaseResponse.lease:type_name -> vaultfs.v1.Lease
	0,  // 8: vaultfs.v1.MasterService.CreateFile:input_type -> vaultfs.v1.CreateFileRequest
	2,  // 9: vaultfs.v1.MasterService.DeleteFile:input_type -> vaultfs.v1.DeleteFileRequest
	4,  // 10: vaultfs.v1.MasterService.Stat:input_type -> vaultfs.v1.StatRequest
	6,  // 11: vaultfs.v1.MasterService.ListDir:input_type -> vaultfs.v1.ListDirRequest
	8,  // 12: vaultfs.v1.MasterService.OpenForRead:input_type -> vaultfs.v1.OpenForReadRequest
	10, // 13: vaultfs.v1.MasterService.OpenForWrite:input_type -> vaultfs.v1.OpenForWriteRequest
	12, // 14: vaultfs.v1.MasterService.FinalizeWrite:input_type -> vaultfs.v1.FinalizeWriteRequest
	14, // 15: vaultfs.v1.MasterService.GetLease:input_type -> vaultfs.v1.GetLeaseRequest
	1,  // 16: vaultfs.v1.MasterService.CreateFile:output_type -> vaultfs.v1.CreateFileResponse
	3,  // 17: vaultfs.v1.MasterService.DeleteFile:output_type -> vaultfs.v1.DeleteFileResponse
	5,  // 18: vaultfs.v1.MasterService.Stat:output_type -> vaultfs.v1.StatResponse
	7,  // 19: vaultfs.v1.MasterService.ListDir:output_type -> vaultfs.v1.ListDirResponse
	9,  // 20: vaultfs.v1.MasterService.OpenForRead:output_type -> vaultfs.v1.OpenForReadResponse
	11, // 21: vaultfs.v1.MasterService.OpenForWrite:output_type -> vaultfs.v1.OpenForWriteResponse
	13, // 22: vaultfs.v1.MasterService.FinalizeWrite:output_type -> vaultfs.v1.FinalizeWriteResponse
	15, // 23: vaultfs.v1.MasterService.GetLease:output_type -> vaultfs.v1.GetLeaseResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vaultfs_v1_master_proto_init() }
func file_vaultfs_v1_master_proto_init() {
	if File_vaultfs_v1_master_proto != nil {
		return
	}
	file_vaultfs_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultfs_v1_master_proto_rawDesc), len(file_vaultfs_v1_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaultfs_v1_master_proto_goTypes,
		DependencyIndexes: file_vaultfs_v1_master_proto_depIdxs,
		MessageInfos:      file_vaultfs_v1_master_proto_msgTypes,
	}.Build()
	File_vaultfs_v1_master_proto = out.File
	file_vaultfs_v1_master_proto_goTypes = nil
	file_vaultfs_v1_master_proto_depIdxs = nil
}
