// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vaultfs/v1/types.proto

// Package vaultfs.v1 defines the shared message types and service contracts
// for the VaultFS distributed filesystem.

package vaultfsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeInfo identifies a chunk server by its stable ID and dial address.
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_vaultfs_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// FileInfo is the metadata for a file or directory in the namespace.
type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size  int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// chunk_ids lists the file's chunks in order. Each ID is a content address
	// (hex-encoded SHA-256 of the chunk bytes).
	ChunkIds      []string `protobuf:"bytes,4,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Mode          uint32   `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	CreatedAtUnix int64    `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64    `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_vaultfs_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *FileInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

// ChunkLocation maps a chunk to the chunk servers that hold (or should hold) a
// replica. By convention nodes[0] is the primary.
type ChunkLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Nodes         []*NodeInfo            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocation) Reset() {
	*x = ChunkLocation{}
	mi := &file_vaultfs_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocation) ProtoMessage() {}

func (x *ChunkLocation) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocation.ProtoReflect.Descriptor instead.
func (*ChunkLocation) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkLocation) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkLocation) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Lease grants a primary chunk server the exclusive right to coordinate writes
// to a chunk until expiry.
type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	ExpiryUnix    int64                  `protobuf:"varint,3,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_vaultfs_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_vaultfs_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_vaultfs_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Lease) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Lease) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Lease) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

var File_vaultfs_v1_types_proto protoreflect.FileDescriptor

const file_vaultfs_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16vaultfs/v1/types.proto\x12\n" +
	"vaultfs.v1\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xca\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tchunk_ids\x18\x04 \x03(\tR\bchunkIds\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\"V\n" +
	"\rChunkLocation\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12*\n" +
	"\x05nodes\x18\x02 \x03(\v2\x14.vaultfs.v1.NodeInfoR\x05nodes\"[\n" +
	"\x05Lease\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x1f\n" +
	"\vexpiry_unix\x18\x03 \x01(\x03R\n" +
	"expiryUnixB\xa0\x01\n" +
	"\x0ecom.vaultfs.v1B\n" +
	"TypesProtoP\x01Z9github.com/sumanthd032/vaultfs/proto/vaultfs/v1;vaultfsv1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vaultfs.V1\xca\x02\n" +
	"Vaultfs\\V1\xe2\x02\x16Vaultfs\\V1\\GPBMetadata\xea\x02\vVaultfs::V1b\x06proto3"

var (
	file_vaultfs_v1_types_proto_rawDescOnce sync.Once
	file_vaultfs_v1_types_proto_rawDescData []byte
)

func file_vaultfs_v1_types_proto_rawDescGZIP() []byte {
	file_vaultfs_v1_types_proto_rawDescOnce.Do(func() {
		file_vaultfs_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultfs_v1_types_proto_rawDesc), len(file_vaultfs_v1_types_proto_rawDesc)))
	})
	return file_vaultfs_v1_types_proto_rawDescData
}

var file_vaultfs_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vaultfs_v1_types_proto_goTypes = []any{
	(*NodeInfo)(nil),      // 0: vaultfs.v1.NodeInfo
	(*FileInfo)(nil),      // 1: vaultfs.v1.FileInfo
	(*ChunkLocation)(nil), // 2: vaultfs.v1.ChunkLocation
	(*Lease)(nil),         // 3: vaultfs.v1.Lease
}
var file_vaultfs_v1_types_proto_depIdxs = []int32{
	0, // 0: vaultfs.v1.ChunkLocation.nodes:type_name -> vaultfs.v1.NodeInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vaultfs_v1_types_proto_init() }
func file_vaultfs_v1_types_proto_init() {
	if File_vaultfs_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultfs_v1_types_proto_rawDesc), len(file_vaultfs_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vaultfs_v1_types_proto_goTypes,
		DependencyIndexes: file_vaultfs_v1_types_proto_depIdxs,
		MessageInfos:      file_vaultfs_v1_types_proto_msgTypes,
	}.Build()
	File_vaultfs_v1_types_proto = out.File
	file_vaultfs_v1_types_proto_goTypes = nil
	file_vaultfs_v1_types_proto_depIdxs = nil
}
